class ResourcesList:
    resources = {
        "active_directory_domain_services": {
            "alphanum": False,
            "global": False,
            "abbr": "adds",
            "dash_allowed": True,
        },
        "api_connection": {
            "alphanum": False,
            "global": False,
            "abbr": "apiconn",
            "dash_allowed": True,
            "max_length": 64,
        },
        "api_management": {
            "alphanum": False,
            "global": False,
            "abbr": "apim",
            "dash_allowed": True,
        },
        "api_management_api": {
            "alphanum": False,
            "global": False,
            "abbr": "aapi",
            "dash_allowed": True,
        },
        "app_configuration": {
            "alphanum": False,
            "global": False,
            "abbr": "appc",
            "dash_allowed": True,
        },
        "app_managed_environment": {
            "alphanum": False,
            "global": False,
            "abbr": "ame",
            "dash_allowed": True,
        },
        "app_service": {
            "alphanum": False,
            "global": False,
            "abbr": "app",
            "dash_allowed": True,
        },
        "app_service_certificates": {
            "alphanum": False,
            "global": False,
            "abbr": "asc",
            "dash_allowed": True,
        },
        "app_service_domain": {
            "alphanum": False,
            "global": False,
            "abbr": "apdr",
            "dash_allowed": True,
        },
        "app_service_plan": {
            "alphanum": False,
            "global": False,
            "abbr": "asp",
            "dash_allowed": True,
        },
        "application_insights": {
            "alphanum": False,
            "global": False,
            "abbr": "ai",
            "dash_allowed": True,
        },
        "application_gateway": {
            "alphanum": False,
            "global": False,
            "abbr": "agw",
            "dash_allowed": True,
        },
        "application_security_group": {
            "alphanum": False,
            "global": False,
            "abbr": "asg",
            "dash_allowed": True,
        },
        "automation_account": {
            "alphanum": False,
            "global": False,
            "abbr": "aa",
            "dash_allowed": True,
        },
        "automation_runbook": {
            "alphanum": False,
            "global": False,
            "abbr": "rb",
            "dash_allowed": True,
        },
        "availability_set": {
            "alphanum": False,
            "global": False,
            "abbr": "as",
            "dash_allowed": True,
        },
        "azure_file_sync": {
            "alphanum": False,
            "global": False,
            "abbr": "afs",
            "dash_allowed": True,
        },
        "azure_firewall": {
            "alphanum": False,
            "global": False,
            "abbr": "afw",
            "dash_allowed": True,
        },
        "azure_maps_account": {
            "alphanum": False,
            "global": False,
            "abbr": "ama",
            "dash_allowed": True,
        },
        "azuread_application": {
            "alphanum": True,
            "global": True,
            "abbr": "aada",
            "dash_allowed": True,
        },
        "backup_container_storage_account": {
            "alphanum": False,
            "global": False,
            "abbr": "st",
            "dash_allowed": True,
        },
        "bastion": {
            "alphanum": False,
            "global": False,
            "abbr": "bas",
            "dash_allowed": True,
        },
        "bastion_host": {
            "alphanum": False,
            "global": False,
            "abbr": "bas",
            "dash_allowed": True,
        },
        "batch_account": {
            "alphanum": False,
            "global": False,
            "abbr": "ba",
            "dash_allowed": True,
        },
        "cdn_endpoint": {
            "alphanum": False,
            "global": False,
            "abbr": "cdne",
            "dash_allowed": True,
        },
        "cdn_profile": {
            "alphanum": False,
            "global": False,
            "abbr": "cdn",
            "dash_allowed": True,
        },
        "cognitive_service": {
            "alphanum": False,
            "global": True,
            "abbr": "cntvs",
            "dash_allowed": True,
            "max_length": 64,
        },
        "cognitive_service_deployment": {
            "alphanum": True,
            "global": True,
            "abbr": "cntbsd",
            "dash_allowed": True,
            "max_length": 64,
        },
        "confluent_organization": {
            "alphanum": True,
            "global": True,
            "abbr": "cnorg",
            "dash_allowed": True,
        },
        "confluent_kafka_cluster": {
            "alphanum": True,
            "global": True,
            "abbr": "cnkfc",
            "dash_allowed": True,
        },
        "confluent_network": {
            "alphanum": True,
            "global": True,
            "abbr": "cnknt",
            "dash_allowed": True,
        },
        "confluent_environment": {
            "alphanum": True,
            "global": True,
            "abbr": "cnenv",
            "dash_allowed": True,
        },
        "container_instance": {
            "alphanum": False,
            "global": False,
            "abbr": "ci",
            "dash_allowed": True,
        },
        "container_registry": {
            "alphanum": True,
            "global": False,
            "abbr": "cr",
            "dash_allowed": False,
        },
        "cosmosdb_account": {
            "alphanum": False,
            "global": False,
            "abbr": "cdb",
            "dash_allowed": True,
        },
        "cosmosdb_sql_database": {
            "alphanum": False,
            "global": False,
            "abbr": "cosmos",
            "dash_allowed": True,
        },
        "cosmosdb_postgresql_cluster": {
            "alphanum": False,
            "global": False,
            "abbr": "psqlc",
            "dash_allowed": True,
        },
        "data_factory": {
            "alphanum": False,
            "global": False,
            "abbr": "df",
            "dash_allowed": True,
        },
        "data_factory_integration_runtime_managed": {
            "alphanum": False,
            "global": False,
            "abbr": "dfirm",
            "dash_allowed": True,
        },
        "data_factory_linked_service_data_lake_storage_gen2": {
            "alphanum": True,
            "global": True,
            "abbr": "lsdlg2",
            "dash_allowed": True,
        },
        "data_factory_linked_service_keyvault": {
            "alphanum": False,
            "global": False,
            "abbr": "lskv",
            "dash_allowed": True,
        },
        "data_factory_linked_service_sql_database": {
            "alphanum": False,
            "global": False,
            "abbr": "lssqldb",
            "dash_allowed": True,
        },
        "data_factory_managed_private_endpoint": {
            "alphanum": True,
            "global": True,
            "abbr": "dfmpe",
            "dash_allowed": True,
        },
        "data_lake_analytics_account": {
            "alphanum": False,
            "global": False,
            "abbr": "adla",
            "dash_allowed": True,
        },
        "data_lake_store": {
            "alphanum": True,
            "global": False,
            "abbr": "adl",
            "dash_allowed": True,
        },
        "databricks_workspace": {
            "alphanum": False,
            "global": False,
            "abbr": "adbr",
            "dash_allowed": True,
        },
        "deployment": {
            "alphanum": False,
            "global": False,
            "abbr": "deploy",
            "dash_allowed": True,
            "max_length": 64,
        },
        "diagnostic_setting": {
            "alphanum": False,
            "global": False,
            "abbr": "diag",
            "dash_allowed": True,
            "max_length": 128,
        },
        "disk_encryption_set": {
            "alphanum": False,
            "global": False,
            "abbr": "des",
            "dash_allowed": True,
        },
        "eventgrid": {
            "alphanum": False,
            "global": False,
            "abbr": "evg",
            "dash_allowed": True,
        },
        "eventhub": {
            "alphanum": False,
            "global": False,
            "abbr": "eh",
            "dash_allowed": True,
        },
        "eventhub_consumer_group": {
            "alphanum": False,
            "global": False,
            "abbr": "ehcg",
            "dash_allowed": True,
        },
        "eventhub_namespace": {
            "alphanum": False,
            "global": False,
            "abbr": "eh",
            "dash_allowed": True,
        },
        "express_route_circuit": {
            "alphanum": False,
            "global": False,
            "abbr": "erc",
            "dash_allowed": True,
        },
        "express_route_gateway": {
            "alphanum": False,
            "global": False,
            "abbr": "egw",
            "dash_allowed": True,
        },
        "firewall": {
            "alphanum": False,
            "global": False,
            "abbr": "afw",
            "dash_allowed": True,
        },
        "frontdoor": {
            "alphanum": False,
            "global": False,
            "abbr": "ftd",
            "dash_allowed": True,
        },
        "function_app": {
            "alphanum": False,
            "global": False,
            "abbr": "func",
            "dash_allowed": True,
        },
        "image": {
            "alphanum": False,
            "global": False,
            "abbr": "img",
            "dash_allowed": True,
        },
        "key_vault": {
            "alphanum": False,
            "global": False,
            "abbr": "kv",
            "dash_allowed": True,
            "max_length": 24,
        },
        "key_vault_access_policy": {
            "alphanum": False,
            "global": False,
            "abbr": "kvap",
            "dash_allowed": True,
        },
        "key_vault_certificate": {
            "alphanum": False,
            "global": False,
            "abbr": "kvcert",
            "dash_allowed": True,
        },
        "key_vault_managed_hsm": {
            "alphanum": True,
            "global": False,
            "abbr": "mhsm",
            "dash_allowed": True,
        },
        "key_vault_key": {
            "alphanum": False,
            "global": False,
            "abbr": "kvk",
            "dash_allowed": True,
            "max_length": 127,
        },
        "key_vault_secret": {
            "alphanum": False,
            "global": False,
            "abbr": "kvs",
            "dash_allowed": True,
        },
        "kubernetes_cluster": {
            "alphanum": False,
            "global": False,
            "abbr": "aks",
            "dash_allowed": True,
        },
        "kubernetes_cluster_node_pool": {
            "alphanum": False,
            "global": False,
            "abbr": "aksnp",
            "dash_allowed": True,
        },
        "kubernetes_node_rg": {
            "alphanum": False,
            "global": False,
            "abbr": "aksrg",
            "dash_allowed": True,
        },
        "kubernetes_service": {
            "alphanum": False,
            "global": False,
            "abbr": "akssr",
            "dash_allowed": True,
        },
        "kusto_cluster": {
            "alphanum": False,
            "global": False,
            "abbr": "kusto",
            "dash_allowed": True,
        },
        "lb": {
            "alphanum": False,
            "global": False,
            "abbr": "lb",
            "dash_allowed": True,
        },
        "lb_backend_address_pool": {
            "alphanum": False,
            "global": False,
            "abbr": "lbp",
            "dash_allowed": True,
        },
        "load_balancer_virtual_ip": {
            "alphanum": False,
            "global": False,
            "abbr": "lbv",
            "dash_allowed": True,
        },
        "log_analytics_linked_service": {
            "alphanum": False,
            "global": False,
            "abbr": "logls",
            "dash_allowed": True,
        },
        "log_analytics_linked_storage_account": {
            "alphanum": False,
            "global": False,
            "abbr": "loglsa",
            "dash_allowed": True,
        },
        "log_analytics_solution": {
            "alphanum": False,
            "global": False,
            "abbr": "las",
            "dash_allowed": True,
        },
        "log_analytics_workspace": {
            "alphanum": False,
            "global": False,
            "abbr": "log",
            "dash_allowed": True,
        },
        "logic_app": {
            "alphanum": False,
            "global": False,
            "abbr": "logic",
            "dash_allowed": True,
            "max_length": 64,
        },
        "managed_disk": {
            "alphanum": False,
            "global": False,
            "abbr": "disk",
            "dash_allowed": True,
            "max_length": 80,
        },
        "managed_identity": {
            "alphanum": False,
            "global": False,
            "abbr": "mid",
            "dash_allowed": True,
        },
        "management_group": {
            "alphanum": False,
            "global": False,
            "abbr": "mg",
            "dash_allowed": True,
        },
        "mysql_database": {
            "alphanum": False,
            "global": False,
            "abbr": "mysql",
            "dash_allowed": True,
        },
        "mysql_server": {
            "alphanum": False,
            "global": False,
            "abbr": "mysqls",
            "dash_allowed": True,
        },
        "nat_gateway": {
            "alphanum": False,
            "global": False,
            "abbr": "natgw",
            "dash_allowed": True,
        },
        "network_ddos_protection_plan": {
            "alphanum": False,
            "global": False,
            "abbr": "ddp",
            "dash_allowed": True,
        },
        "network_interface": {
            "alphanum": False,
            "global": False,
            "abbr": "nic",
            "dash_allowed": True,
        },
        "network_security_group": {
            "alphanum": False,
            "global": False,
            "abbr": "nsg",
            "dash_allowed": True,
        },
        "network_security_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "nsgr",
            "dash_allowed": True,
        },
        "network_watcher": {
            "alphanum": False,
            "global": False,
            "abbr": "nw",
            "dash_allowed": True,
        },
        "network_watcher_flow_log": {
            "alphanum": False,
            "global": False,
            "abbr": "flow",
            "dash_allowed": True,
        },
        "policy_assignment": {
            "alphanum": False,
            "global": True,
            "abbr": "pa",
            "dash_allowed": True,
            "max_length": 24,
        },
        "postgresql_server": {
            "alphanum": True,
            "global": False,
            "abbr": "psql",
            "dash_allowed": True,
        },
        "private_dns_a_record": {
            "alphanum": False,
            "global": False,
            "abbr": "pdnsar",
            "dash_allowed": True,
        },
        "private_dns_cname_record": {
            "alphanum": False,
            "global": False,
            "abbr": "pdnscr",
            "dash_allowed": True,
        },
        "private_dns_zone": {
            "alphanum": False,
            "global": False,
            "abbr": "pdnsz",
            "dash_allowed": True,
        },
        "private_dns_zone_group": {
            "alphanum": "False",
            "global": False,
            "abbr": "pdnszg",
            "dash_allowed": True,
        },
        "private_endpoint": {
            "alphanum": False,
            "global": False,
            "abbr": "pe",
            "dash_allowed": True,
            "max_length": 64,
        },
        "public_ip": {
            "alphanum": False,
            "global": False,
            "abbr": "pip",
            "dash_allowed": True,
        },
        "public_ip_prefix": {
            "alphanum": False,
            "global": False,
            "abbr": "ippre",
            "dash_allowed": True,
        },
        "purview_account": {
            "alphanum": False,
            "global": False,
            "abbr": "pur",
            "dash_allowed": True,
        },
        "recovery_services_vault": {
            "alphanum": False,
            "global": False,
            "abbr": "rsv",
            "dash_allowed": True,
        },
        "recovery_services_protection_policy": {
            "alphanum": False,
            "global": False,
            "abbr": "rspp",
            "dash_allowed": True,
        },
        "recovery_services_protected_item": {
            "alphanum": False,
            "global": False,
            "abbr": "rspi",
            "dash_allowed": True,
        },
        "redis_cache": {
            "alphanum": False,
            "global": False,
            "abbr": "arc",
            "dash_allowed": True,
        },
        "redis_firewall_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "redisfwr",
            "dash_allowed": True,
        },
        "redis_linked_server": {
            "alphanum": False,
            "global": False,
            "abbr": "rsv",
            "dash_allowed": True,
        },
        "resource_group": {
            "abbr": "rg",
            "alphanum": False,
            "global": False,
            "dash_allowed": True,
            "max_length": 90,
        },
        "route_table": {
            "alphanum": False,
            "global": False,
            "abbr": "udr",
            "dash_allowed": True,
        },
        "sentinel": {
            "alphanum": False,
            "global": False,
            "abbr": "sot",
            "dash_allowed": True,
        },
        "sentinel_automation_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "aut",
            "dash_allowed": True,
            "max_length": 64,
        },
        "service_fabric_cluster": {
            "alphanum": False,
            "global": False,
            "abbr": "svfc",
            "dash_allowed": True,
        },
        "servicebus_namespace": {
            "alphanum": False,
            "global": False,
            "abbr": "sbn",
            "dash_allowed": True,
        },
        "servicebus_queue": {
            "alphanum": False,
            "global": False,
            "abbr": "sbq",
            "dash_allowed": True,
        },
        "shared_image_definition": {
            "alphanum": False,
            "global": False,
            "abbr": "sid",
            "dash_allowed": True,
        },
        "shared_image_gallery": {
            "alphanum": True,
            "global": False,
            "abbr": "sig",
            "dash_allowed": False,
        },
        "shared_image_version": {
            "alphanum": False,
            "global": False,
            "abbr": "siv",
            "dash_allowed": True,
        },
        "signalr": {
            "alphanum": False,
            "global": False,
            "abbr": "sr",
            "dash_allowed": True,
        },
        "sql_data_warehouse": {
            "alphanum": False,
            "global": False,
            "abbr": "sqdw",
            "dash_allowed": True,
        },
        "sql_database": {
            "alphanum": False,
            "global": False,
            "abbr": "sqdb",
            "dash_allowed": True,
        },
        "sql_managed_database": {
            "alphanum": False,
            "global": False,
            "abbr": "sqmdb",
            "dash_allowed": True,
        },
        "sql_managed_instance": {
            "alphanum": False,
            "global": False,
            "abbr": "sqmi",
            "dash_allowed": True,
        },
        "sql_server": {
            "alphanum": False,
            "global": False,
            "abbr": "sql",
            "dash_allowed": True,
        },
        "ssh_public_key": {
            "alphanum": False,
            "global": False,
            "abbr": "sshkey",
            "dash_allowed": True,
        },
        "static_web_app": {
            "alphanum": False,
            "global": False,
            "abbr": "stapp",
            "dash_allowed": True,
        },
        "storage_account": {
            "alphanum": False,
            "global": False,
            "abbr": "sa",
            "dash_allowed": False,
            "max_length": 24,
        },
        "storage_account_network_rules": {
            "alphanum": True,
            "global": True,
            "abbr": "sanr",
            "dash_allowed": True,
        },
        "storage_queue": {
            "alphanum": True,
            "global": True,
            "abbr": "sq",
            "dash_allowed": True,
        },
        "storage_blob": {
            "alphanum": True,
            "global": True,
            "abbr": "sb",
            "dash_allowed": True,
        },
        "storage_container": {
            "alphanum": True,
            "global": True,
            "abbr": "sc",
            "dash_allowed": True,
        },
        "storage_management_policy": {
            "alphanum": True,
            "global": True,
            "abbr": "samp",
            "dash_allowed": True,
        },
        "subnet": {
            "alphanum": False,
            "global": False,
            "abbr": "snet",
            "dash_allowed": True,
        },
        "subscription": {
            "alphanum": False,
            "global": False,
            "abbr": "sub",
            "dash_allowed": True,
        },
        "synapse_firewall_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "synfw",
            "dash_allowed": True,
        },
        "synapse_managed_private_endpoint": {
            "alphanum": False,
            "global": False,
            "abbr": "synmpe",
            "dash_allowed": True,
        },
        "synapse_spark_pool": {
            "alphanum": False,
            "global": False,
            "abbr": "synspp",
            "dash_allowed": True,
        },
        "synapse_sql_pool": {
            "alphanum": False,
            "global": False,
            "abbr": "synsqlp",
            "dash_allowed": True,
        },
        "synapse_workspace": {
            "alphanum": False,
            "global": False,
            "abbr": "synw",
            "dash_allowed": True,
        },
        "traffic_manager_profile": {
            "alphanum": False,
            "global": False,
            "abbr": "tm",
            "dash_allowed": True,
        },
        "user_assigned_identity": {
            "alphanum": False,
            "global": False,
            "abbr": "id",
            "dash_allowed": True,
        },
        "virtual_machine": {
            "alphanum": False,
            "global": False,
            "abbr": "vm",
            "dash_allowed": True,
        },
        "virtual_machine_scale_set": {
            "alphanum": False,
            "global": False,
            "abbr": "vmss",
            "dash_allowed": True,
        },
        "virtual_network": {
            "alphanum": False,
            "global": False,
            "abbr": "vnet",
            "dash_allowed": True,
        },
        "vpn_gateway": {
            "alphanum": False,
            "global": False,
            "abbr": "vpn",
            "dash_allowed": True,
        },
        "web_application_firewall_policy": {
            "alphanum": False,
            "global": False,
            "abbr": "wafp",
            "dash_allowed": True,
        },
        "scheduled_alert_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "sar",
            "dash_allowed": True,
        },
        "templated_alert_rule": {
            "alphanum": False,
            "global": False,
            "abbr": "tar",
            "dash_allowed": True,
        },
    }

    def __init__(self):
        pass
